### ISSUE TITLE
考虑适配在阿里云云函数/腾讯云云函数/华为云函数工作流等云函数上运行吗

### ISSUE THREAD

**Issue by cxw620** [david082321/BiliRoaming-PHP-Server#31]
如题. 这样服务器可靠性大大提高, 而且成本也比购买服务器低. 自建难度也大大降低.
我不会php, 所以问一下. 或者等暑假有空了我自己写一个python或者nodejs版本的.
不过已知数据库的问题有点难解决, 云函数不允许写数据到本地, 数据存储的问题我在移植FODI项目的时候是通过API连接到Cloudflare Worker KV曲线解决的

**Comment by M1saka10010** [comment]
woker的kv太慢了，等请求到了解析都超时了emm...单纯移植到云函数其实并不难。如果你想降低成本又想稳定，可以考虑大厂的云虚机。

**Comment by david082321** [comment]
如果自用的话，不用数据库其实是可以的。
数据库只是因为公共的太多人用，服务器短时间请求太多会被B站风控。

有人写了go语言的，可以参考一下
https://github.com/JasonKhew96/biliroaming-go-server

**Comment by M1saka10010** [comment]
> 如果自用的话，不用数据库其实是可以的。 数据库只是因为公共的太多人用，服务器短时间请求太多会被B站风控。
> 
> 有人写了go语言的，可以参考一下 https://github.com/JasonKhew96/biliroaming-go-server

如果不用数据库，有现成的啊emm https://github.com/zzc10086/grocery_store/tree/master/bili_proxy

**Comment by cxw620** [comment]
> woker的kv太慢了，等请求到了解析都超时了emm...单纯移植到云函数其实并不难。如果你想降低成本又想稳定，可以考虑大厂的云虚机。

已经跟华为云的研发说过, 可能会上线原生的类似KV的功能
此外可以参考下这个? 把sqlite存对象存储里面: https://www.taterli.com/5490/

**Comment by M1saka10010** [comment]
> > woker的kv太慢了，等请求到了解析都超时了emm...单纯移植到云函数其实并不难。如果你想降低成本又想稳定，可以考虑大厂的云虚机。
> 
> 已经跟华为云的研发说过, 可能会上线原生的类似KV的功能 此外可以参考下这个? 把sqlite存对象存储里面: https://www.taterli.com/5490/

先不说对象存储的并发性能如何，单说sqlite本身，如果想要并发读写是不可能的，多人请求的性能可想而知。在番剧刚更新的时候的半个小时请求量可是相当大的，不过如果华为云会出个类似kv的功能，那还有点意思，你可以试着造个nodejs的轮子

**Comment by cxw620** [comment]
> > > woker的kv太慢了，等请求到了解析都超时了emm...单纯移植到云函数其实并不难。如果你想降低成本又想稳定，可以考虑大厂的云虚机。
> > 
> > 
> > 已经跟华为云的研发说过, 可能会上线原生的类似KV的功能 此外可以参考下这个? 把sqlite存对象存储里面: https://www.taterli.com/5490/
> 
> 先不说对象存储的并发性能如何，单说sqlite本身，如果想要并发读写是不可能的，多人请求的性能可想而知。在番剧刚更新的时候的半个小时请求量可是相当大的，不过如果华为云会出个类似kv的功能，那还有点意思，你可以试着造个nodejs的轮子

确实. 不过华为云那边出不出也不知道, 轮子有时间了就先备好看看后续吧.
