### ISSUE TITLE
9721b8f 版本一直返回 -20 ERROR

### ISSUE THREAD

**Issue by xxxxuanran** [david082321/BiliRoaming-PHP-Server#33]
直接 Git clone 之后，[目前版本](https://github.com/david082321/BiliRoaming-PHP-Server/commit/9721b8f7e3ddae2ec7ac038dbd7fbeb423f63d53) 会一直返回 -20 ERROR 访问密钥缺失。
当我回退到 [该版本](https://github.com/david082321/BiliRoaming-PHP-Server/tree/e6d931118d5037879b93905d4c2bcca496621621) 时，正常使用没有问题。
中间版本因时间关系未能逐一验证，望作者能抽空修复。如果作者无法复现或需要日志，可以留下邮箱，我提供目前正在使用的机器供您操作。

**Comment by david082321** [comment]
请问你 config.php 里的这三个设置成什么？
1. SAVE_CACHE
2. NEED_LOGIN
3. BLOCK_TYPE

我尝试复现看看

**Comment by xxxxuanran** [comment]
![image](https://user-images.githubusercontent.com/31968665/171985947-e56ee86b-10a2-488a-80a2-6bdaa4f6418c.png)

这是 [9721b8f 版本](https://github.com/david082321/BiliRoaming-PHP-Server/tree/9721b8f7e3ddae2ec7ac038dbd7fbeb423f63d53) 的 config.php 配置内容，我仅修改了 WEB_ON 参数。

在 [解除B站区域限制](https://greasyfork.org/zh-CN/scripts/25718-%E8%A7%A3%E9%99%A4b%E7%AB%99%E5%8C%BA%E5%9F%9F%E9%99%90%E5%88%B6) 脚本中清楚授权后重新授权，仍会出现如下错误：

![image](https://user-images.githubusercontent.com/31968665/171986393-0ae66fe2-046e-44ce-a8a8-e9250112a899.png)

***

![image](https://user-images.githubusercontent.com/31968665/171986261-95023978-e891-4c26-bd15-82cd1bbc56a0.png)

这是 [e6d9311 版本](https://github.com/david082321/BiliRoaming-PHP-Server/tree/e6d931118d5037879b93905d4c2bcca496621621) 的 config.php 配置内容，同样仅修改了 WEB_ON 参数，同样的脚本设置（未重新获取授权），可以正常播放

![image](https://user-images.githubusercontent.com/31968665/171986290-54eca553-fb93-4d92-8b77-f32473849d39.png)

***

测试时使用的番剧链接：[不會拿捏距離的阿波連同學（僅限港澳台地區）](https://www.bilibili.com/bangumi/play/ss41458)

**Comment by david082321** [comment]
你把 这行 的内容改成 `exit($output);`

然后看一下返回什么内容？

我怀疑是这里出问题

https://github.com/david082321/BiliRoaming-PHP-Server/blob/9721b8f7e3ddae2ec7ac038dbd7fbeb423f63d53/utils/functions.php#L137

**Comment by xxxxuanran** [comment]
![image](https://user-images.githubusercontent.com/31968665/171987247-b484fd14-61e2-4e47-a713-18ff994772db.png)

按您说的修改之后：

![image](https://user-images.githubusercontent.com/31968665/171987265-1408614a-0089-40cf-ba79-d9b4c4c2109d.png)

以及 浏览器 console 的 输出（已脱敏）：

[www.bilibili.com-1654323410165.log](https://github.com/david082321/BiliRoaming-PHP-Server/files/8837143/www.bilibili.com-1654323410165.log)

**Comment by david082321** [comment]
看来我猜的没错，再把刚刚那行改成这个

`exit("appkey=".APPKEY."&ts=".TS."&appsec=".$appsec);`

一样发一下脚本提示错误的内容

这次就能修好了（应该

**Comment by xxxxuanran** [comment]
![image](https://user-images.githubusercontent.com/31968665/171987627-bb35a18d-f7d8-4998-95f8-3a4b8333a6b9.png)

脚本返回内容以及日志

[www.bilibili.com-1654324225232.log](https://github.com/david082321/BiliRoaming-PHP-Server/files/8837155/www.bilibili.com-1654324225232.log)

**Comment by david082321** [comment]
怪事，脚本没有传appkey

**Comment by david082321** [comment]
@xxxxuanran 
改了，你试试看
https://github.com/david082321/BiliRoaming-PHP-Server/commit/bc3efc0be8b2fd38ecfd5d8519f5e2be0df1bccc

ps. 对了，上面修改的记得改回来

**Comment by xxxxuanran** [comment]
![image](https://user-images.githubusercontent.com/31968665/171987858-955b463b-6377-474c-950d-767d15cf2467.png)

脚本应该是有传 appkey 的，这是 [e6d9311 版本](https://github.com/david082321/BiliRoaming-PHP-Server/commit/e6d931118d5037879b93905d4c2bcca496621621) 的返回内容

**Comment by david082321** [comment]
> ![image](https://user-images.githubusercontent.com/31968665/171987858-955b463b-6377-474c-950d-767d15cf2467.png)
> 
> 脚本应该是有传 appkey 的，这是 [e6d9311 版本](https://github.com/david082321/BiliRoaming-PHP-Server/commit/e6d931118d5037879b93905d4c2bcca496621621) 的返回内容

这里不准，我原本有自带appkey，原本是强制复写

**Comment by xxxxuanran** [comment]
已经正常使用，感谢作者抽空解决。先关闭 issue 了。
