### ISSUE TITLE
问一下这两天换了域名，结果速度突然大降甚至有时候上不去，有可能是什么情况

### ISSUE THREAD

**Issue by JSTks24** [david082321/BiliRoaming-PHP-Server#38]
如题
这两天从原来的top渔民换到了cn域名，结果现在进番速度大降

甚至不做伪静态的话根本看不了，做伪静态也只会特别特别慢，原来都是秒进的

想问问有可能是哪方面的问题

电报我前段时间莫名被永封了，所以不能在群里发，所以在这里issue了

**Comment by david082321** [comment]
先清空数据库，不会清的直接删掉重来。

然后考虑一下，有没有可能是域名问题？

**Comment by david082321** [comment]
长时间未回复，关闭issue
