### ISSUE TITLE
An error in afea6b9 version

### ISSUE THREAD

**Issue by GirlKiller512** [david082321/BiliRoaming-PHP-Server#40]
拉取了最新的版本 (afea6b9) 部署在服务器的宝塔面板上，已配置防重复 301 转址
Web 端油猴脚本和 App 端哔哩漫游都填好了服务器的域名
App 端打开番剧一切正常，Web 端首次打开番剧会弹出一大串东西，必须多刷新一次才能看
不确定是油猴脚本的问题还是程序的问题
![image](https://user-images.githubusercontent.com/20424975/210262048-2fcf7dad-96ba-4c6a-b69a-e306a2ae2cb2.png)
如果去掉防重复 301 转址后直接不能看了
![image](https://user-images.githubusercontent.com/20424975/210264544-6f624f12-cfd4-41dd-a939-486ace397f9d.png)
**服务器环境：**
Ubuntu 20.04.5
Nginx 1.23.2
MySQL 5.7.40
PHP 8.2.0
**程序配置：**
（和拉取的 config.php 不同的地方）
`BLOCK_TYPE` = local_whitelist
`NEED_LOGIN` = 1
`BILIROAMING` = 0
`WEB_ON` = 1
`SAVE_CACHE` = 1
`SAVE_LOG` = 1

**Comment by david082321** [comment]
试试看有没有问题

**Comment by GirlKiller512** [comment]
和朋友测试了一下，可以了
禁用 301 转址的代码不能去掉，去掉后不能看，弹出的错误和第 2 张图一样，只要写了就能看

**Comment by david082321** [comment]
@GirlKiller512 
防止301转址的功能，本来就是给脚本用的。
不加的话，漫游可以用，脚本不能用。
