### ISSUE TITLE
关于新版的随机调用

### ISSUE THREAD

**Issue by hanasaki-misaki** [david082321/BiliRoaming-PHP-Server#41]
// 自定义API,避免集中请求，降低风控几率
$hk_api = array('host1','host2','host3'); // 随机调用HK，可以自定义其他反代api，例如云函数、CFW，请自行修改 host1~3 的內容，启用要注释上方默认api
$tw_api = array('host1','host2','host3'); // 随机调用TW，可以自定义其他反代api，例如云函数、CFW，请自行修改 host1~3 的內容，启用要注释上方默认api
if (CUSTOM_HOST_HK == "CUSTOM_HOST_HK") {
	define('CUSTOM_HOST_HK', $hk_api[array_rand($hk_api)]); // 随机调用HK
}
if (CUSTOM_HOST_TW == "CUSTOM_HOST_TW") {
	define('CUSTOM_HOST_TW', $tw_api[array_rand($tw_api)]); // 随机调用TW
}

如果注释掉上方的默认API则下面的if判断会丢失掉赋值
所以要怎么搞？

**Comment by david082321** [comment]
你试过注释之后，会提示什么报错吗？

**Comment by hanasaki-misaki** [comment]
现在有新的问题了，漫游日志中显示timeout回传参数是参数ts错误(E=17)
关于试过注释之后，会提示报错为CUSTOM_HOST_HK未赋值
@david082321
