### ISSUE TITLE
最近出现的大会员限制问题

### ISSUE THREAD

**Issue by AzusaHana** [david082321/BiliRoaming-PHP-Server#42]
Web 端问题，App 端正常
油猴脚本版本 8.4.3
测试两个账号都拥有大会员
在观看需要大会员的番剧时，会提示 {"code":-10403,"message":"大会员专享限制"}
但是在观看非会员的番剧时，能够正常选择大会员的清晰度

自建服务器
Ubuntu 22.04.2
Nginx 1.24.0
MySQL 5.7.42
PHP 8.2.8
服务器为白名单模式
![e98ded45d41913a9cd1e88d28d09e4a5](https://github.com/david082321/BiliRoaming-PHP-Server/assets/100906636/3832e385-c824-4584-aa1e-2299c2654fa3)

在出现问题的当天测试 哔哩.plus 服务器（Go）也有相同问题，当天晚上就能拉取了，问该服务器作者说并不清楚 php 端的缓存

**Comment by david082321** [comment]
No more information.
