### ISSUE TITLE
服务器不可用

### ISSUE THREAD

**Issue by CGangel** [david082321/BiliRoaming-PHP-Server#44]
腾讯云的香港服务器，centos7.9版本，宝塔，网站搭建成功，采用本地白名单模式，但是哔哩漫游仍然提示服务器不可用
![Screenshot_20231019_065651_com huawei browser_edit_26887793258397](https://github.com/david082321/BiliRoaming-PHP-Server/assets/104315535/cc21735d-7510-49a0-972a-c3758f9a000c)
![Screenshot_20231019_065742_tv danmaku bili_edit_26930826502661](https://github.com/david082321/BiliRoaming-PHP-Server/assets/104315535/abcbc4f2-bb19-45fb-b94b-55a9b87191c0)

**Comment by CodePwn2021** [comment]
开了SSL没

**Comment by david082321** [comment]
已私下联络后修复

**Comment by sxsjs123** [comment]
问题一致搭建成功 但是无法使用

**Comment by U29kaXVt** [comment]
> 问题一致搭建成功 但是无法使用

配置下SSL就可以用了

**Comment by sxsjs123** [comment]
> > 问题一致搭建成功 但是无法使用
> 
> 配置下SSL就可以用了
对不起我没有提供的我的环境。  php放在docker容器中   可以稍微指导一下怎么配置嘛。感谢

**Comment by sxsjs123** [comment]
感谢提供思路 已经成功解决
