### ISSUE TITLE
请问一下显示成功了但是漫游还是显示服务器不可用是为啥o(╥﹏╥)o

### ISSUE THREAD

**Issue by jobbbbb** [david082321/BiliRoaming-PHP-Server#47]
![1698037133803](https://github.com/david082321/BiliRoaming-PHP-Server/assets/62783941/fde78a1a-7c4d-4cc8-b27c-9e6f7482184f)

**Comment by Night-stars-1** [comment]
需要配置ssl

**Comment by jobbbbb** [comment]
> 需要配置ssl

谢谢
